"""Step 2: execute every query in the .sql file, save each output as CSV + a combined Markdown report."""
import re, sqlite3
from pathlib import Path
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sql = (ROOT / "sql/task23_window_functions.sql").read_text(encoding="utf-8")
con = sqlite3.connect(ROOT / "northwind.db")

# split on "-- Qn:" title lines
parts = re.split(r"(?m)^-- (Q\d+): (.*)$", sql)
# parts = [preamble, 'Q1', title, body, 'Q2', title, body ...]
md = ["# Query Outputs - Task 23 (SQL Window Functions)\n",
      "_All outputs generated by running `sql/task23_window_functions.sql` on `northwind.db` (SQLite)._\n"]
for i in range(1, len(parts), 3):
    qid, title, body = parts[i], parts[i+1], parts[i+2]
    # the executable statement = from first WITH/SELECT to first ';'
    stmt = body[re.search(r"(?m)^(WITH|SELECT)", body).start():]
    stmt = stmt[: stmt.index(";") + 1]
    df = pd.read_sql_query(stmt, con)
    n = int(qid[1:])
    df.to_csv(ROOT / f"outputs/{qid.lower()}_output.csv", index=False)
    md.append(f"\n## {qid}: {title}\n")
    md.append("```sql\n" + stmt + "\n```\n")
    md.append(f"**Output ({len(df)} rows):**\n")
    md.append(df.to_markdown(index=False) + "\n")
    print(f"{qid}: {len(df)} rows OK")
(ROOT / "outputs/all_query_outputs.md").write_text("\n".join(md), encoding="utf-8")
